resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master
 
pipelines:
  - name: pipeline1
    setup:
   #   environmentVariables:
   #     readOnly:
    #      ENV1: value1
    #      ENV2: value2 
      runtime:       
        type: image
        image:
         #auto:
          #  language: nodeJs
          #  versions: 
          #    - 8.15.0
          custom:
            name: drydock/u16nodall
            tag: latest
             #options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'
    steps:    
      - name: testJob1
        type: bash
       # configuration:
         # affinityGroup: bldGroup 
         # priority: <[0-10000]>
        #  timeoutSeconds: 7/8
         # nodePool: testing__u16nodepool
        setup:
       #   environmentVariables:
        #    normal:
         #     ENV1: value1
         #     ENV3: value3
         #     STEP_TYPE: test
          runtime:       
            type: host
            #image:
           
            #auto:
              #language: nodeJs
              #versions: 
                #- 8.15.0
            #custom:
              
              #name: drydock/u16nodall
              #tag: latest
               #options: '--privileged=true --net=bridge -e FOO=true -e BOO=false'
        requires:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - printenv
            - node -v
            - echo "hello!"
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onSuccess:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onComplete:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onStart:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onFailure:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onCancel:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            
      - name: testJobTest2
        type: bash
        triggeredBy:
          steps:
            - testJob1
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            
  - name: pipeline2
    steps:    
      - name: step_pl2
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
            encrypted:
              ENV2: d1bCzOYy8NOVwcEiO+XDHibr3k7xz59tg/M7vOaWXDELm7Z7xAQe3nRqFIQyWcKA4XRN4REe6fIRp1Tuw7X6eTWLuqUyhTRIpwzyXFDk91/OYSEXE7Iyd9Hslq8DA33IU4k66Ekrg5/qIvByV10ViV8RVDvXZj1kG29xjKvlVq6QZ6XPvU9cP7jplfrXBQTH42dITSjwEu+/vaobhObcm6xj5AsGDylYxTnJG08/6kurOjeYmlOmnj4JMqUNY8t5GvGl7AE+d4dA9/OdTfxsDZ/SYDALwy/qrtnXOfE7uynvfvl/JYy1T7aXXiYI6zDaJGdxRXpgognn71jvND5mAg==
       # triggeredBy:
        #  resources:
         #   - sample_scriptrepo
        execution:
          onExecute:
            - printenv
