resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        only: pipe
    initialVersion:
      sha: master
      
  - name: imageDoc
    type: image
    imageName: shippabledocker/sample_node
    configuration:
      integrationName: dockerInt
    initialVersion:
      imageTag: latest
 
pipelines:
  - name: pipeline1
    steps:  
      - name: testJob1
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV3: value3
              STEP_TYPE: update
              PIPELINE_NAME: update
              STEP_NAME: update
         #     RUNNING_IN_CONTAINER: container #this throw error when i update this
            secure:
              ENV2: EpEMlpUSs85U6Y5WmsV5xXUr/GkDpuKP0qH6yy4qPoTbZUSRwmIwWhez+bNSmDJe7lkZN1+syxU1LFmt09QqtSVQpy69brIW1L6vLaHVtBn7hcYGC3dJhmvXUYn/ohpasFj/sab6lwXHQSs+nRYyFRF+ICRzoTB6M17JW/KoLpqJrLL1hBYC1gPSXuWgJT/ZqKWcg+GWhCZT1o9L6IrHrgaMYR3aSmWwGAZoUBWGuTw7/datT6NDhxD6nX64dRdcR+4X0yRnTLPzbxqiMC9qTBw4ChIw5CenyH0tE/AF6YlhoavkyyRBkgd18AQKVNpQneaRN7htnIe+fLEsbKEkwQ==
        triggeredBy:
          resources:
            - sample_scriptrepo
          integrations:
            - dockerInt
        runtime:            
          type: image
          image:
            custom:
              name: drydock/u16all
              tag: v7.2.4
              options: 'privileged: true'
        execution:
          onExecute:
            - printenv
            - echo "hello!"
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
          #  - echo "RUNNING_IN_CONTAINER=$RUNNING_IN_CONTAINER"
          onSuccess:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onComplete:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
          onStart:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onFailure:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
          onCancel:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            
      - name: step_2
        type: bash
        triggeredBy:
          resources:
            - imageDoc
          steps:
            - testJob1
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
            
      - name: step_3
        type: bash
        configuration:
          priority: 2
        triggeredBy:
          steps:
            - testJob1
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
            
      - name: step_4
        type: bash
        configuration:
          priority: 1
        triggeredBy:
          steps:
            - testJob1
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
            
  - name: pipeline2
    steps:    
      - name: step_pl2
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
            encrypted:
              ENV2: d1bCzOYy8NOVwcEiO+XDHibr3k7xz59tg/M7vOaWXDELm7Z7xAQe3nRqFIQyWcKA4XRN4REe6fIRp1Tuw7X6eTWLuqUyhTRIpwzyXFDk91/OYSEXE7Iyd9Hslq8DA33IU4k66Ekrg5/qIvByV10ViV8RVDvXZj1kG29xjKvlVq6QZ6XPvU9cP7jplfrXBQTH42dITSjwEu+/vaobhObcm6xj5AsGDylYxTnJG08/6kurOjeYmlOmnj4JMqUNY8t5GvGl7AE+d4dA9/OdTfxsDZ/SYDALwy/qrtnXOfE7uynvfvl/JYy1T7aXXiYI6zDaJGdxRXpgognn71jvND5mAg==
       # triggeredBy:
        #  resources:
         #   - sample_scriptrepo
        execution:
          onExecute:
            - printenv
