resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master
  
pipelines:
  - name: pipeline1
    setup:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2 
      runtime:       
        type: host
        image:
          auto:
            language: python
            versions: 
              - 3.6
    steps:    
      - name: testJob1
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
            encrypted:
              ENV2: d1bCzOYy8NOVwcEiO+XDHibr3k7xz59tg/M7vOaWXDELm7Z7xAQe3nRqFIQyWcKA4XRN4REe6fIRp1Tuw7X6eTWLuqUyhTRIpwzyXFDk91/OYSEXE7Iyd9Hslq8DA33IU4k66Ekrg5/qIvByV10ViV8RVDvXZj1kG29xjKvlVq6QZ6XPvU9cP7jplfrXBQTH42dITSjwEu+/vaobhObcm6xj5AsGDylYxTnJG08/6kurOjeYmlOmnj4JMqUNY8t5GvGl7AE+d4dA9/OdTfxsDZ/SYDALwy/qrtnXOfE7uynvfvl/JYy1T7aXXiYI6zDaJGdxRXpgognn71jvND5mAg==
       # triggeredBy:
        #  resources:
         #   - sample_scriptrepo
        execution:
          onExecute:
            - printenv
            - echo "hello!"
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            
      - name: testJob2
        type: bash
        triggeredBy:
          steps:
            - testJob1
        setup:
          runtime:            
            type: image
            image:
              auto:
                language: python
                versions: 
                  - 3.6
             # custom:
              #  name:
             #   tag:
              #  options:
   
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
