resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        only: master
  
pipelines:
  - name: pipeline1
    setup:
      environmentVariables:
        readOnly:
          - ENV1: value1
          - ENV2: value2 
    steps:    
      - name: testJob1
        type: bash
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - echo "hello!"
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            
      - name: testJob2
        type: bash
        triggeredBy:
          steps:
            - testJob1
        execution:
          onExecute:
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
